---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ dnsmasq_dependencies }}"
    state: present
    update_cache: true

- name: Setup configuration files
  ansible.builtin.template:
    dest: /etc/dnsmasq.d/{{ item.key }}
    group: root
    mode: 0644
    owner: root
    src: conf.j2
    validate: 'dnsmasq --test -C %s'
  loop: "{{ dnsmasq_conf | dict2items }}"
  notify: Restart dnsmasq

- name: Ensure dnsmasq is started and starts on boot
  ansible.builtin.service:
    enabled: true
    name: dnsmasq
    state: started
